version: "3.9"
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: masar
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env.example
    environment:
      DEBUG: "False"
      DB_ENGINE: postgres
      DB_NAME: masar
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      ALLOWED_HOSTS: 127.0.0.1,localhost
      CORS_ALLOW_ALL_ORIGINS: "True"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    command: sh -c "python manage.py migrate && python manage.py seed_demo_data && gunicorn config.wsgi:application --bind 0.0.0.0:8000"

volumes:
  postgres_data:
