# Generated by Django 6.0.4 on 2026-05-05 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('container_no', models.CharField(max_length=30)),
                ('bl_no', models.CharField(blank=True, max_length=80, null=True)),
                ('vessel_name', models.CharField(blank=True, max_length=160, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('arrival_port', models.CharField(blank=True, max_length=160, null=True)),
                ('destination', models.CharField(max_length=255)),
                ('release_document', models.FileField(blank=True, null=True, upload_to='release_documents/')),
                ('status', models.CharField(choices=[('DRAFT', '?????'), ('VERIFIED', '?? ??????'), ('OFFERS_SENT', '?? ????? ??????'), ('CARRIER_SELECTED', '?? ?????? ???? ?????'), ('PAID', '?????'), ('DRIVER_ASSIGNED', '?? ????? ??????'), ('PORT_SLOT_BOOKED', '?? ??? ???? ???????'), ('QR_ISSUED', '?? ????? QR'), ('COMPLETED', '?????'), ('CANCELLED', '????')], default='DRAFT', max_length=30)),
                ('agreed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_requests', to='core.driver')),
                ('assigned_truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_requests', to='core.truck')),
                ('linked_trip', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_request', to='core.trip')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_requests', to=settings.AUTH_USER_MODEL)),
                ('selected_carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_transport_requests', to='core.company')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_requests', to='core.bookingslot')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TransportPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(default='manual', max_length=60)),
                ('status', models.CharField(choices=[('PENDING', '????'), ('PAID', '?????'), ('FAILED', '???'), ('REFUNDED', '??????')], default='PENDING', max_length=20)),
                ('transaction_ref', models.CharField(blank=True, max_length=160, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='core.transportrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransportOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_pickup_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', '????'), ('ACCEPTED', '?????'), ('REJECTED', '?????')], default='PENDING', max_length=20)),
                ('carrier_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_offers', to='core.company')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='core.transportrequest')),
            ],
            options={
                'ordering': ('price', 'created_at'),
                'unique_together': {('request', 'carrier_company')},
            },
        ),
    ]
