# Generated by Django 6.0.4 on 2026-05-29 05:07

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transportrequest_transportpayment_transportoffer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ('-created_at',), 'verbose_name': 'سجل مراجعة', 'verbose_name_plural': 'سجلات المراجعة'},
        ),
        migrations.AlterModelOptions(
            name='bookingslot',
            options={'ordering': ('date', 'hour'), 'verbose_name': 'نافذة حجز', 'verbose_name_plural': 'نوافذ الحجز'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('name',), 'verbose_name': 'شركة', 'verbose_name_plural': 'الشركات'},
        ),
        migrations.AlterModelOptions(
            name='container',
            options={'ordering': ('container_no',), 'verbose_name': 'حاوية', 'verbose_name_plural': 'الحاويات'},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ('full_name',), 'verbose_name': 'سائق', 'verbose_name_plural': 'السائقين'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created_at',), 'verbose_name': 'إشعار', 'verbose_name_plural': 'الإشعارات'},
        ),
        migrations.AlterModelOptions(
            name='scanevent',
            options={'ordering': ('-scanned_at',), 'verbose_name': 'حدث مسح', 'verbose_name_plural': 'أحداث المسح'},
        ),
        migrations.AlterModelOptions(
            name='scanpoint',
            options={'ordering': ('name',), 'verbose_name': 'نقطة مسح', 'verbose_name_plural': 'نقاط المسح'},
        ),
        migrations.AlterModelOptions(
            name='transportoffer',
            options={'ordering': ('price', 'created_at'), 'verbose_name': 'عرض نقل', 'verbose_name_plural': 'عروض النقل'},
        ),
        migrations.AlterModelOptions(
            name='transportpayment',
            options={'verbose_name': 'دفعة نقل', 'verbose_name_plural': 'دفعات النقل'},
        ),
        migrations.AlterModelOptions(
            name='transportrequest',
            options={'ordering': ('-created_at',), 'verbose_name': 'طلب نقل', 'verbose_name_plural': 'طلبات النقل'},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ('-created_at',), 'verbose_name': 'رحلة', 'verbose_name_plural': 'الرحلات'},
        ),
        migrations.AlterModelOptions(
            name='truck',
            options={'ordering': ('plate_number',), 'verbose_name': 'شاحنة', 'verbose_name_plural': 'الشاحنات'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'ملف المستخدم', 'verbose_name_plural': 'ملفات المستخدمين'},
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='model_name',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='bookingslot',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='bookingslot',
            name='hour',
            field=models.PositiveIntegerField(help_text='0-23', validators=[django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AlterField(
            model_name='bookingslot',
            name='is_closed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('broker', 'مخلص'), ('carrier', 'ناقل'), ('port', 'ميناء'), ('customs', 'جمارك'), ('other', 'أخرى')], db_index=True, default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='container',
            name='customs_status',
            field=models.CharField(db_index=True, default='released', max_length=50),
        ),
        migrations.AlterField(
            model_name='container',
            name='destination',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='driver',
            name='national_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='transportoffer',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transportoffer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('ACCEPTED', 'مقبول'), ('REJECTED', 'مرفوض')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='transportpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transportpayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('PAID', 'مدفوع'), ('FAILED', 'فشل'), ('REFUNDED', 'مسترد')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='container_no',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'مسودة'), ('VERIFIED', 'تم التحقق'), ('OFFERS_SENT', 'تم إرسال العروض'), ('CARRIER_SELECTED', 'تم اختيار شركة النقل'), ('PAID', 'مدفوع'), ('DRIVER_ASSIGNED', 'تم تعيين السائق'), ('PORT_SLOT_BOOKED', 'تم حجز موعد الميناء'), ('QR_ISSUED', 'تم إصدار QR'), ('COMPLETED', 'مكتمل'), ('CANCELLED', 'ملغي')], db_index=True, default='DRAFT', max_length=30),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('CREATED', 'تم الإنشاء'), ('BOOKED', 'محجوزة'), ('APPROVED', 'معتمدة'), ('ARRIVED_GATE', 'وصلت البوابة'), ('ENTERED_PORT', 'داخل الميناء'), ('AT_BERTH', 'في الرصيف'), ('LOADING_COMPLETE', 'اكتمل التحميل'), ('PASSED_CUSTOMS', 'اجتازت الجمارك'), ('EXITED_PORT', 'خرجت من الميناء'), ('IN_TRANSIT', 'في الطريق'), ('DELIVERED', 'تم التسليم'), ('CANCELLED', 'ملغاة')], db_index=True, default='CREATED', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('broker', 'مخلص جمركي'), ('carrier', 'شركة نقل'), ('gate_guard', 'حارس بوابة'), ('port_admin', 'إدارة الميناء'), ('ops', 'عمليات')], db_index=True, default='broker', max_length=20),
        ),
        migrations.AddIndex(
            model_name='bookingslot',
            index=models.Index(fields=['date', 'hour'], name='idx_slot_date_hour'),
        ),
        migrations.AddIndex(
            model_name='bookingslot',
            index=models.Index(fields=['date', 'is_closed'], name='idx_slot_date_closed'),
        ),
        migrations.AddIndex(
            model_name='scanevent',
            index=models.Index(fields=['trip', 'scan_point'], name='idx_scan_trip_point'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status', 'created_at'], name='idx_trip_status_created'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['broker', 'status'], name='idx_trip_broker_status'),
        ),
    ]
